In [79]:
import numpy as np
import re
from scipy.spatial import distance

In [80]:
words = []
word_c = 0
line_c = 0
diction = {}
with open('sentences.txt', 'r') as file:
    num_lines = len(file.readlines())
    file.seek(0)
    for line in file:
        sentence = re.split('\W+', line.lower())
        for word in sentence[:-1]:
            if word not in diction:
                diction[word]={
                        "sentence": word_c,
                        "event": [0] * num_lines
                                }
                word_c += 1
            elif diction[word]["event"][line_c] != 0:
                continue
            diction[word]["event"][line_c] = sentence.count(word)
         
        line_c += 1
print (diction)

{'in': {'sentence': 0, 'event': [1, 0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0]}, 'comparison': {'sentence': 1, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, 'to': {'sentence': 2, 'event': [1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 0, 1, 1]}, 'dogs': {'sentence': 3, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, 'cats': {'sentence': 4, 'event': [1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, 'have': {'sentence': 5, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]}, 'not': {'sentence': 6, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, 'undergone': {'sentence': 7, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, 'major': {'sentence': 8, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]}, 'changes': {'sentence': 9, 'event': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [81]:
array = np.zeros((num_lines, len(diction)))

In [82]:
for key in diction:
    i, j = 0, diction[key]['sentence']
    for event in diction[key]['event']:
        array[i, j] = event
        i += 1
print (array)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [83]:
dist = []
u = array[0]
for i in range(1, num_lines):
    v = array[i]
    dist.append({'sentence': i, 'distance' : distance.cosine(u, v)})

In [84]:
dist.sort(key=lambda x: x['distance'])
print (*dist[0:2])


{'sentence': 6, 'distance': 0.7673789474003823} {'sentence': 4, 'distance': 0.7770887149698589}
